let tableObject = {
    "table": {
        "name": "enrollmentItem",
        "attributesSimpleArray": [
            "title",
            "_id",
            "_owner",
            "_createdDate",
            "_updatedDate",
            "ZZZstudentFirst",
            "studentLast",
            "parentFirst",
            "parentLast",
            "idPP",
            "jsonEnrollment",
            "jsonCorollary",
            "jsonStatusNotes"
        ],
        "attributes": {
            "title": {
                "key": "title",
                "name": "Title",
                "source": "form",
                "usage": "display only",
                "dataType": "Text",
                "notes": [
                    "default format is 'Miley Cyrus (Billy Ray)",
                    "alt format is 'Angelina Jolie (Jon Voight)",
                    "other formats possible, as this is merely for display it's _data_ is elsewhere"
                ]
            },
            "_id": {
                "key": "_id",
                "name": "ID",
                "source": "WiX Velo",
                "usage": "necessary for database robustness",
                "dataType": "Text",
                "notes": [
                    "any field where the key starts with an underscore is generated by WiX",
                    "...and cannot be altered for any given record or deleted from the table"
                ]
            },
            "_owner": {
                "key": "_owner",
                "name": "Owner",
                "source": "WiX Velo",
                "usage": "necessary for database robustness",
                "dataType": "Text",
                "notes": [
                    "any field where the key starts with an underscore is generated by WiX",
                    "...and cannot be altered for any given record or deleted from the table"
                ]
            },
            "_createdDate": {
                "key": "_createdDate",
                "name": "Created Date",
                "source": "WiX Velo",
                "usage": "necessary for database robustness",
                "dataType": "Date and Time",
                "notes": [
                    "any field where the key starts with an underscore is generated by WiX",
                    "...and cannot be altered for any given record or deleted from the table"
                ]
            },
            "_updatedDate": {
                "key": "_updatedDate",
                "name": "Updated Date",
                "source": "WiX Velo",
                "usage": "necessary for database robustness",
                "dataType": "Date and Time",
                "notes": [
                    "any field where the key starts with an underscore is generated by WiX",
                    "...and cannot be altered for any given record or deleted from the table"
                ]
            },
            "idST": {
                "key": "idStudent",
                "name": "Student Last",
                "source": "person table",
                "usage": "one of two Compound Keys",
                "dataType": "Text",
                "notes": []
            },
            "studentDisplay": {
                "key": "studentDisplay",
                "name": "Student Name",
                "source": "enrollment form",
                "usage": "human identification",
                "dataType": "Text",
                "notes": []
            },
            "jsonStudent": {
                "key": "jsonStudent",
                "name": "Student Last",
                "source": "enrollment form",
                "usage": "human identification",
                "dataType": "Text",
                "notes": []
            },
            "idCS": {
                "key": "idCS",
                "name": "Course ID",
                "source": "WiX Velo by way of 'Summer Courses'_id",
                "usage": "used to connect Parent with Member with any and all Enrollments for her/his children",
                "dataType": "Text",
                "notes": [
                    "idCS covers both 'Course' and 'Class' which are interchangeable",
                    "in a sense this makes Family ID redundant, but still good to have Family ID so that it is its own thing",
                    "in geek talk, using the Family ID makes everything more 'extensible'",
                    "it is permissible, for this table, for this value to be 'INSTANTIATE'"
                ]
            },
            "idQK": {
                "key": "idQK",
                "name": "Quick Key ID",
                "source": "SteamDA to link FormStack and Course Table",
                "usage": "used to connect Parent with Member with any and all Enrollments for her/his children",
                "dataType": "Text",
                "notes": [
                    "because the 'true' _id was too long to show on FormStack confirmation Emails",
                    "in a sense this makes Family ID redundant, but still good to have Family ID so that it is its own thing",
                    "in geek talk, using the Family ID makes everything more 'extensible'",
                    "it is permissible, for this table, for this value to be 'INSTANTIATE'"
                ]
            },
            "jsonCourse": {
                "key": "idQK",
                "name": "Quick Key ID",
                "source": "SteamDA to link FormStack and Course Table",
                "usage": "used to connect Parent with Member with any and all Enrollments for her/his children",
                "dataType": "Text",
                "notes": [
                    "because the 'true' _id was too long to show on FormStack confirmation Emails",
                    "in a sense this makes Family ID redundant, but still good to have Family ID so that it is its own thing",
                    "in geek talk, using the Family ID makes everything more 'extensible'",
                    "it is permissible, for this table, for this value to be 'INSTANTIATE'"
                ]
            },
            "idPP": {
                "key": "idPP",
                "name": "Primary Parent ID",
                "source": "WiX Velo by way of automated Parent Membership",
                "usage": "used to connect Parent with Member with any and all Enrollments for her/his children",
                "dataType": "Text",
                "notes": [
                    "in a sense this makes Family ID redundant, but still good to have Family ID so that it is its own thing",
                    "in geek talk, using the Family ID makes everything more 'extensible'",
                    "it is permissible, for this table, for this value to be 'INSTANTIATE'"
                ]
            },
            "parentDisplay": {
                "key": "parentLast",
                "name": "Parent Last",
                "source": "enrollment form",
                "usage": "human identification",
                "dataType": "Text",
                "notes": []
            },
            "jsonCorollary": {
                "key": "jsonCorollary",
                "name": "Corollary JSON",
                "source": "if any, 'Webhook Processing' dashboard process",
                "usage": "unknown",
                "dataType": "Text",
                "notes": [
                    "for the same reasons every other table has 'jsonCorollary'",
                    "yet in this instance it is _highly_ likely not to be used",
                    "probably good to insert an empty JSON Object,'{}'"
                ]
            },
            "jsonStatusNotes": {
                "key": "jsonStatusNotes",
                "name": "Status Notes JSON",
                "source": "logic",
                "usage": "discrete values to describe the status of the Enrollment",
                "dataType": "Text",
                "notes": [
                    "since every Status is another element in this JSON, used for Attendance too",
                    "---",
                    "PRESENT",
                    "---",
                    "EXCUSED ABSENCE",
                    "UNEXCUSED ABSENCE",
                    "---",
                    "ENROLLED",
                    "---",
                    "COMPLETED",
                    "GRADUATED",
                    "PASSED",
                    "FAILED",
                    "---",
                    "WITHDRAWN",
                    "---",
                    "EXPELLED"
                ]
            }
        }
    }
};

let attributes = Object.keys(tableObject.table.attributes);
console.log(attributes)