//union100[41]: 

let union100 = [ 'memory.getItem(ppMemberPrepJSON)',
  'local.getItem(ondeckEnrollmentJSON)',
  'memory.getItem(ppMemberExecuteUpsert)',
  'local.getItem(staffIdentifiedFamilyId)',
  'local.getItem(termId)',
  'memory.getItem(stMemberPrepJSON)',
  'local.getItem(familyId)',
  'local.getItem(termLabelKey)',
  'memory.getItem(stMemberExecuteUpsert)',
  'local.getItem(studentId)',
  'local.getItem(weekIdToLabelKeyJSON)',
  'memory.getItem(ppContactPrepJSON)',
  'local.getItem(termBeginMMDD)',
  'memory.getItem(ppDatabasePrepJSON)',
  'local.getItem(termEndMMDD)',
  'memory.getItem(stContactPrepJSON)',
  'local.getItem(loopExitAfterStep)',
  'memory.getItem(stDatabasePrepJSON)',
  'memory.getItem(enrollmentStepCompleted)',
  'memory.getItem(spContactPrepJSON)',
  'memory.getItem(enrollmentStepList)',
  'memory.getItem(spDatabasePrepJSON)',
  'memory.getItem(loopExitNow)',
  'memory.getItem(ppContactExecuteUpsert)',
  'memory.getItem(ppRevision)',
  'memory.getItem(ppDatabaseExecuteUpsert)',
  'memory.getItem(stContactExecuteUpsert)',
  'memory.getItem(ppMemberOnDeckJSON)',
  'memory.getItem(stDatabaseExecuteUpsert)',
  'memory.getItem(yyyymm)',
  'memory.getItem(spContactExecuteUpsert)',
  'memory.getItem(enrollmentStepCurrent)',
  'memory.getItem(spDatabaseExecuteUpsert)',
  'memory.getItem(stepStampArray)',
  'local.getItem(wixWebhookId)',
  'memory.getItem(HHOLDER)',
  'memory.getItem(enrollmentStepNext)',
  'local.getItem(loopExitNow)',
  'memory.getItem(loopExitAfterStep)',
  'memory.getItem(stRevision)',
  'local.getItem(yyyymm)' ]


//union100_local[13]: 

let union100_local = [ 'local.getItem(ondeckEnrollmentJSON)',
  'local.getItem(staffIdentifiedFamilyId)',
  'local.getItem(termId)',
  'local.getItem(familyId)',
  'local.getItem(termLabelKey)',
  'local.getItem(studentId)',
  'local.getItem(weekIdToLabelKeyJSON)',
  'local.getItem(termBeginMMDD)',
  'local.getItem(termEndMMDD)',
  'local.getItem(loopExitAfterStep)',
  'local.getItem(wixWebhookId)',
  'local.getItem(loopExitNow)',
  'local.getItem(yyyymm)' ];

//union100_session[0]: 

let union100_session = [];

//union100_memory[28]: 

let union100_memory = [ 'memory.getItem(ppMemberPrepJSON)',
  'memory.getItem(ppMemberExecuteUpsert)',
  'memory.getItem(stMemberPrepJSON)',
  'memory.getItem(stMemberExecuteUpsert)',
  'memory.getItem(ppContactPrepJSON)',
  'memory.getItem(ppDatabasePrepJSON)',
  'memory.getItem(stContactPrepJSON)',
  'memory.getItem(stDatabasePrepJSON)',
  'memory.getItem(enrollmentStepCompleted)',
  'memory.getItem(spContactPrepJSON)',
  'memory.getItem(enrollmentStepList)',
  'memory.getItem(spDatabasePrepJSON)',
  'memory.getItem(loopExitNow)',
  'memory.getItem(ppContactExecuteUpsert)',
  'memory.getItem(ppRevision)',
  'memory.getItem(ppDatabaseExecuteUpsert)',
  'memory.getItem(stContactExecuteUpsert)',
  'memory.getItem(ppMemberOnDeckJSON)',
  'memory.getItem(stDatabaseExecuteUpsert)',
  'memory.getItem(yyyymm)',
  'memory.getItem(spContactExecuteUpsert)',
  'memory.getItem(enrollmentStepCurrent)',
  'memory.getItem(spDatabaseExecuteUpsert)',
  'memory.getItem(stepStampArray)',
  'memory.getItem(HHOLDER)',
  'memory.getItem(enrollmentStepNext)',
  'memory.getItem(loopExitAfterStep)',
  'memory.getItem(stRevision)' ];
